{"name": "test_productPage", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nThe chromedriver version cannot be discovered", "trace": "request = <SubRequest 'beforeClass' for <TestCaseFunction test_enterDetails>>\n\n    @pytest.fixture(scope='class')\n    def beforeClass(request):\n        print('Before Class')\n        driver1 = WebDriverClass()\n>       driver = driver1.get_web_driver(\"chrome\")\n\nconftest.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\DriverClass.py:8: in get_web_driver\n    driver = webdriver.Chrome()\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py:82: in __init__\n    service.path = DriverFinder.get_path(service, options)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py:43: in get_path\n    raise err\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py:40: in get_path\n    path = shutil.which(service.path) or SeleniumManager().driver_location(options)\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py:101: in driver_location\n    result = self.run(args)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ['C:\\\\Users\\\\vs34\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python311\\\\Lib\\\\site-packages\\\\selenium\\\\webdriver\\\\common\\\\windows\\\\selenium-manager.exe', '--browser', 'chrome', '--output', 'json']\n\n    @staticmethod\n    def run(args: List[str]) -> str:\n        \"\"\"\n        Executes the Selenium Manager Binary.\n        :Args:\n         - args: the components of the command being executed.\n        :Returns: The log string containing the driver location.\n        \"\"\"\n        command = \" \".join(args)\n        logger.info(f\"Executing: {command}\")\n        completed_proc = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)\n        stdout = completed_proc.stdout.decode(\"utf-8\").rstrip(\"\\n\")\n        stderr = completed_proc.stderr.decode(\"utf-8\").rstrip(\"\\n\")\n        output = json.loads(stdout)\n        result = output[\"result\"][\"message\"]\n        if completed_proc.returncode:\n>           raise SeleniumManagerException(f\"Selenium Manager failed for: {command}.\\n{result}{stderr}\")\nE           selenium.common.exceptions.SeleniumManagerException: Message: Selenium Manager failed for: C:\\Users\\vs34\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nE           The chromedriver version cannot be discovered\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\common\\selenium_manager.py:122: SeleniumManagerException"}, "start": 1708590360030, "stop": 1708590360030, "uuid": "cbb4b929-da2c-4926-8352-7bdc2182a6d8", "historyId": "c4ebccab08adc41f9fb1bce91e5994a2", "testCaseId": "c4ebccab08adc41f9fb1bce91e5994a2", "fullName": "TestSuite.AddCartTest#test_productPage", "labels": [{"name": "tag", "value": "run(order=9)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "AddCartTest"}, {"name": "host", "value": "GESLLR0D3LS8"}, {"name": "thread", "value": "19680-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuite"}]}